server:
  port: 8080
  debug: true
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/repair
    username: musyimi
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false